### PR TITLE
Update format.sh

### PR DESCRIPTION
**Pull request by jhferris**
TLDR probably shouldn't be formatting those to our style anyway, and there is a file with spaces in there that breaks stuff.

### CODE REVIEW

**Comment by g-easy** [comment]
Where does `_deps` come from?

The only mention I can find is in `cmake/FetchContent.cmake` which results in `.build/_deps` which should already be excluded on line 23 (where `.build` is excluded)

What am I missing?

**Comment by jhferris** [comment]
Something in the build process makes a top level _deps directory:

ferrisj@feisbox:~/opencensus-cpp$ ag -g spaces
_deps/prometheus-src/3rdparty/civetweb/test/dir with spaces/hello.cgi

I got this from the error in CI from my other PR as well as trying to run it locally.

**Comment by g-easy** [comment]
How are you running CMake? I was not able to repro this on my workstation with CMake 3.10.2 and following the instructions in `cmake/README.md`

**Comment by jhferris** [comment]
I hadn't seen the README in the cmake dir (I'd checked the toplevel README and didn't see anything).

I was building with just `cmake .`

**Comment by g-easy** [comment]
This seems like a common enough pattern that it's worth special-casing `_deps`.

**Pull request merged**
