### PR TITLE
CMake: Replace ExternalProject_Add with FetchContent

### PR DESCRIPTION
**Pull request by meastp**
This reduces the amount of code for including/building dependencies. ~~The only drawback is an increase in the CMake version required.~~

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@g-easy this looks good to me (from a person with 0 knowledge about cmake, but I like when code gets deleted). What do you think?

**Comment by meastp** [comment]
We already discussed it in #244, but I'd like @g-easy to look at it anyway :)

**Comment by g-easy** [comment]
Please make this pass on Travis. :)

**Comment by meastp** [comment]
Well, I can't run the tools/format.sh script as I'm on Windows. Could you help me with that like last time? :)

The other failure is simply because the travis node's CMake version is too old:

> CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
> CMake 3.11 or higher is required.  You are running version 3.9.2

**Comment by bogdandrutu** [comment]
@meastp you can create a small docker image map your clone directory, and run the script :) maybe we should have a "tools/format_docker.sh" which actually is useful not only for your usecase but also to make sure that we run that specific clang-format.

**Comment by meastp** [comment]
> 
> 
> @meastp you can create a small docker image map your clone directory, and run the script :) maybe we should have a "tools/format_docker.sh" which actually is useful not only for your usecase but also to make sure that we run that specific clang-format.

What if travis could just push a commit to the pull request with the required changes if the tools/format.sh fails? :)

https://gist.github.com/willprice/e07efd73fb7f13f917ea

**Comment by g-easy** [comment]
Regular Xenial ships cmake 3.5.1. I got this running locally with ubuntu:cosmic. https://launchpad.net/ubuntu/+source/cmake

**Comment by g-easy** [comment]
@coryan Is the cmake 3.11 requirement okay with you?

**Comment by coryan** [comment]
And Ubuntu:bionic is 3.10, and let's not get started on CentOS.  I think 3.11 might be too high given the current versions on popular distros.

**Comment by meastp** [comment]
What about including `FetchContent` directly, then, as was suggested in https://github.com/census-instrumentation/opencensus-cpp/pull/256#issuecomment-448406031?

**Comment by g-easy** [comment]
I think `FetchContent.cmake` is worth a try. What is the minimum version requirement with this option?

**Comment by meastp** [comment]
@coryan @g-easy It looks like this works with the old cmake versions. :) 

@g-easy Could you please fix format.sh for me?

**Pull request merged**
